"""empty message

Revision ID: 11f09899fd7f
Revises: bce6c84de2fa
Create Date: 2022-05-08 13:29:55.471191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f09899fd7f'
down_revision = 'bce6c84de2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('look_for_venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('look_for_venues_description', sa.String(length=500), nullable=True))
    op.drop_column('Artist', 'website')
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_Show_venue_id_Venue'), 'Show', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(op.f('fk_Show_artist_id_Artist'), 'Show', 'Artist', ['artist_id'], ['id'])
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('look_for_artists', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('look_for_artists_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'look_for_artists_description')
    op.drop_column('Venue', 'look_for_artists')
    op.drop_column('Venue', 'website_link')
    op.drop_constraint(op.f('fk_Show_artist_id_Artist'), 'Show', type_='foreignkey')
    op.drop_constraint(op.f('fk_Show_venue_id_Venue'), 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    op.add_column('Artist', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'look_for_venues_description')
    op.drop_column('Artist', 'look_for_venues')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
