"""empty message

Revision ID: a3198e9c2bf5
Revises: 2541b80fb8c8
Create Date: 2022-11-01 21:35:48.641644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3198e9c2bf5'
down_revision = '2541b80fb8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('Availability', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('Show', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('Venue', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created_at')
    op.drop_column('Show', 'created_at')
    op.drop_column('Availability', 'created_at')
    op.drop_column('Artist', 'created_at')
    # ### end Alembic commands ###
